apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: node
        image: us-central1-docker.pkg.dev/fady-401509/my-repository/fadyelyas/node-app:v1
        ports:
        - containerPort: 27017
        env:
        - name: DBuser
          value: "fady"
        - name: DBpass
          value: "123"
        - name: DBhosts
          value: "mongo-0.mongo,mongo-1.mongo,mongo-2.mongo"
