apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reader-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: mongo-srvice-acc
  namespace: default
roleRef:
  kind: Role
  name: reader-role
  apiGroup: rbac.authorization.k8s.io
